### ISSUE TITLE
front-end-hello-world.bat fails at user input

### ISSUE THREAD

**Issue by jonathan-besanceney** [PredixDev/guided-tutorials#2]
Hi,

I'm trying to perform the Hello World Front-End Web App Tutorial.
The bat script proposed in the «What you need to do» section is not working when it asks :
Should we install the required tools if not already installed?

Looking in the script (damn, BATCH is hell !) I found that the answer variable is not initialized before using it. The strings are not quoted in the SET /p commands. It interferes when SET assign the return value. Some string tests in :VERIFY_ANSWER are not working on my machine.

Here is a tested proposal of modification  :  [front-end-hello-world.zip](https://github.com/PredixDev/guided-tutorials/files/883076/front-end-hello-world.zip)
 
Hope this will help,
Regards,
Jonathan

**Comment by turnerth** [comment]
We've been doing some testing and have also validated that the script is not working as expected.  Though the solution was solved with some use of quotes in the verify.  This is part of a much larger release which is coming soon.  Will use your example to ensure it's working as expected before next release.
