### ISSUE TITLE
running the command to "run the guided tutorial" does not work on windows

### ISSUE THREAD

**Issue by Abdelkrim** [PredixDev/guided-tutorials#3]
**Executing the following command line** described in https://github.com/PredixDev/guided-tutorials

@powershell -Command "(new-object net.webclient).DownloadFile('https://raw.githubusercontent.com/PredixDev/guided-tutorials/master/<tutorial>.bat','%TEMP%\<tutorial>.bat')" && "%TEMP%\<tutorial>.bat"

**Generates the following error message**

Exception calling "DownloadFile" with "2" argument(s): "An exception occurred during a WebClient request."
At line:1 char:1
+ (new-object net.webclient).DownloadFile('https://raw.githubuserconten ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

**QUESTION:** Could you please provide a correct documentation?

**Comment by gstroup** [comment]
Which tutorial are you trying to run?  We're eventually going to deprecate the tutorials in this repo.  We're moving them into "quickstart" scripts in the repo along with the codebases.  Here's a tutorial showing how to run it for the RMD reference app:
https://www.predix.io/resources/tutorials/tutorial-details.html?tutorial_id=2106&tag=1610&journey=Digital%20Twin%3A%20from%20the%20Edge%20to%20the%20Cloud%20using%20RMD%20Reference%20App&resources=1592,1473,2106,1600

**Comment by Abdelkrim** [comment]
OK thank you. I have changed my methods: I download the files manually and run them.


PS: I have found out that Git Bash" IS NOT supported and that powershell
